In [6]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:Malkhed%40123@localhost/datana")
tables= pd.read_sql("SHOW TABLES", con=engine)
tables.columns=['name']
tables

                    name
0        begin_inventory
1          end_inventory
2        purchase_prices
3              purchases
4                  sales
5         vendor_invoice
6  vendors_sales_summary

In [2]:
for table in tables['name']:
    print('-'*50,f'{table}','-'*50)
    print('Count of records:',pd.read_sql(f"select count(*) as count from {table}",con=engine)['count'].values[0])
    display(pd.read_sql(f"select * from {table} limit 5" ,engine))

-------------------------------------------------- begin_inventory --------------------------------------------------
Count of records: 206529

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,8,12.99,2024-01-01
1,1_HARDERSFIELD_60,1,HARDERSFIELD,60,Canadian Club 1858 VAP,750mL,7,10.99,2024-01-01
2,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,6,36.99,2024-01-01
3,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,3,38.99,2024-01-01
4,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,6,34.99,2024-01-01

-------------------------------------------------- end_inventory --------------------------------------------------
Count of records: 224489

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,endDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,11,12.99,2024-12-31
1,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,7,36.99,2024-12-31
2,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,7,38.99,2024-12-31
3,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,4,34.99,2024-12-31
4,1_HARDERSFIELD_75,1,HARDERSFIELD,75,Three Olives Tomato Vodka,750mL,7,14.99,2024-12-31

-------------------------------------------------- purchase_prices --------------------------------------------------
Count of records: 12261

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.

-------------------------------------------------- purchases --------------------------------------------------
Count of records: 2372474

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5,106.60,1

-------------------------------------------------- sales --------------------------------------------------
Count of records: 12825363

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-01,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,2024-01-02,750.0,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-03,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,2024-01-08,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,2024-01-09,375.0,1,0.79,12546,JIM BEAM BRANDS COMPANY

-------------------------------------------------- vendor_invoice --------------------------------------------------
Count of records: 5543

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,None
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,None
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,None

-------------------------------------------------- vendors_sales_summary --------------------------------------------------
Count of records: 6780

,index,VendorNumber,VendorName,Brand,PurchasePrice,Volume,TotalSalesPrice,TotalSalesQuantity,TotalSalesDollars,TotalExciseTax,totalQuantity,totalPPrice,FreightCost,ActualPrice,Description,GrossProfit,ProfitMargin,StockTurnover,SalesTOPurchaseRatio
0,0,1128,BROWN-FORMAN CORP,1233,26.27,1750.0,672819.31,142049.0,5.101920e+06,260999.20,145080.0,3811251.60,68601.68,36.99,Jack Daniels No 7 Black,1290667.91,25.297693,0.979108,1.338647
1,1,4425,MARTIGNETTI COMPANIES,3405,23.19,1750.0,561512.37,160247.0,4.819073e+06,294438.66,164038.0,3804041.22,144929.24,28.99,Tito's Handmade Vodka,1015032.27,21.062810,0.976890,1.266830
2,2,17035,PERNOD RICARD USA,8068,18.24,1750.0,461140.15,187140.0,4.538121e+06,343854.07,187407.0,3418303.68,123780.22,24.99,Absolut 80 Proof,1119816.92,24.675786,0.998575,1.327594
3,3,3960,DIAGEO NORTH AMERICA INC,4261,16.17,1750.0,420050.01,200412.0,4.475973e+06,368242.80,201682.0,3261197.94,257032.07,22.99,Capt Morgan Spiced Rum,1214774.94,27.139908,0.993703,1.372493
4,4,3960,DIAGEO NORTH AMERICA INC,3545,21.89,1750.0,545778.28,135838.0,4.223108e+06,249587.83,138109.0,3023206.01,257032.07,29.99,Ketel One Vodka,1199901.61,28.412764,0.983556,1.396897

In [3]:
p=pd.read_sql('select * from purchases  where VendorNumber=4466 ',engine)
p

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
1,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
2,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
3,38_GOULCREST_5215,38,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2023-12-27,2024-01-07,2024-01-19,2024-02-26,9.41,6,56.46,1
4,59_CLAETHORPES_5215,59,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2023-12-27,2024-01-05,2024-01-19,2024-02-26,9.41,6,56.46,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2187,81_PEMBROKE_5215,81,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-29,2025-01-04,2025-02-10,9.41,6,56.46,1
2188,62_KILMARNOCK_5255,62,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-28,2025-01-04,2025-02-10,9.35,5,46.75,1
2189,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-28,2025-01-04,2025-02-10,9.41,5,47.05,1
2190,6_GOULCREST_5215,6,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-31,2025-01-04,2025-02-10,9.41,6,56.46,1
2191,35_HALIVAARA_5255,35,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-27,2025-01-04,2025-02-10,9.35,5,46.75,1

In [108]:
p.groupby(['Brand','PurchasePrice'])[['Quantity','Dollars']].sum()

                     Quantity   Dollars
Brand PurchasePrice
3140  11.19              4640  51921.60
5215  9.41               4923  46325.43
5255  9.35               6215  58110.25

In [4]:
s=pd.read_sql('select * from sales where VendorNo=4466',engine)
s

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-09,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
1,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-12,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
2,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-15,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
3,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-21,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
4,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-23,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9448,9_BLACKPOOL_5215,9,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-12-21,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9449,9_BLACKPOOL_5255,9,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-02,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9450,9_BLACKPOOL_5255,9,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-09,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9451,9_BLACKPOOL_5255,9,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-23,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9452,9_BLACKPOOL_5255,9,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-31,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE

In [120]:
s.groupby(['Brand','SalesPrice'])[['SalesQuantity','SalesDollars']].sum()

                  SalesQuantity  SalesDollars
Brand SalesPrice
3140  12.99                3890      50531.10
5215  12.99                4651      60416.49
5255  12.99                6096      79187.04

In [121]:
a=pd.read_sql('select * from vendor_invoice ',engine)
a

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,None
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,None
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,None
...,...,...,...,...,...,...,...,...,...,...
5538,9622,WEIN BAUER INC,2025-01-06,13626,2024-12-21,2025-02-10,90,1563.00,8.60,None
5539,9625,WESTERN SPIRITS BEVERAGE CO,2025-01-10,13661,2024-12-23,2025-02-18,4617,37300.48,186.50,None
5540,3664,WILLIAM GRANT & SONS INC,2025-01-02,13643,2024-12-22,2025-02-04,9848,202815.78,932.95,None
5541,9815,WINE GROUP INC,2025-01-03,13602,2024-12-20,2025-02-08,24747,149007.56,819.54,None
5542,90058,ZORVINO VINEYARDS,2025-01-05,13574,2024-12-18,2025-02-12,437,3608.11,16.60,None

In [122]:
p.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'VendorNumber',
       'VendorName', 'PONumber', 'PODate', 'ReceivingDate', 'InvoiceDate',
       'PayDate', 'PurchasePrice', 'Quantity', 'Dollars', 'Classification'],
      dtype='object')

In [123]:
f=pd.read_sql_query(""" select  VendorNumber, sum(Freight) as f_cost from  vendor_invoice 
group by VendorNumber """,engine)
f

     VendorNumber    f_cost
0             105     62.39
1            4466    793.91
2             388    211.74
3             480  89286.27
4             516   8510.41
..            ...       ...
121        201359      0.09
122          4901      0.72
123         90059     74.84
124          5083     10.68
125            54      0.48

[126 rows x 2 columns]

In [115]:
 p.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'VendorNumber',
       'VendorName', 'PONumber', 'PODate', 'ReceivingDate', 'InvoiceDate',
       'PayDate', 'PurchasePrice', 'Quantity', 'Dollars', 'Classification'],
      dtype='object')

In [124]:
pd.read_sql("""
    SELECT 
        p.VendorNumber,
        p.VendorName,
        p.Brand,
        p.PurchasePrice,
        pp.Volume,
        pp.Price AS ActualPrice,
        SUM(p.Quantity) AS totalQuantity,
        SUM(p.Dollars) AS totalPPrice
    FROM purchases p
    JOIN purchase_prices pp
        ON p.Brand = pp.Brand
    WHERE p.PurchasePrice>0
    GROUP BY 
        p.VendorNumber,
        p.VendorName,
        p.Brand,
        p.PurchasePrice,
        pp.Volume,
        pp.Price
""", engine)

,VendorNumber,VendorName,Brand,PurchasePrice,Volume,ActualPrice,totalQuantity,totalPPrice
0,105,ALTAMAR BRANDS LLC,8412,35.71,750,49.99,320.0,11427.20
1,4466,AMERICAN VINTAGE BEVERAGE,5255,9.35,1750,12.99,6215.0,58110.25
2,4466,AMERICAN VINTAGE BEVERAGE,5215,9.41,1750,12.99,4923.0,46325.43
3,480,BACARDI USA INC,3348,22.38,1750,29.99,57349.0,1283470.62
4,480,BACARDI USA INC,8358,14.49,750,19.99,7071.0,102458.79
...,...,...,...,...,...,...,...,...
10687,4425,MARTIGNETTI COMPANIES,28007,12.41,750,18.99,120.0,1489.20
10688,7153,PINE STATE TRADING CO,26508,6.81,750,10.49,1.0,6.81
10689,8004,SAZERAC CO INC,2936,53.02,750,69.99,18.0,954.36
10690,2000,SOUTHERN WINE & SPIRITS NE,26266,11.56,750,16.99,132.0,1525.92
10691,9165,ULTRA BEVERAGE COMPANY LLP,1073,25.73,750,34.99,168.0,4322.64

In [127]:
s.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'SalesQuantity',
       'SalesDollars', 'SalesPrice', 'SalesDate', 'Volume', 'Classification',
       'ExciseTax', 'VendorNo', 'VendorName'],
      dtype='object')

In [131]:
pd.read_sql(
    """  select 
    VendorNo,
    Brand,
    sum(SalesPrice) as TotalSalesPrice,
    sum(SalesQuantity) as TotalSalesQuantity,
    sum(SalesDollars) as TotalSalesDollars,
    sum(ExciseTax) as TotalExciseTax
    from sales
    group by VendorNo,
    Brand
    order by TotalSalesDollars""",engine)

,VendorNo,Brand,TotalSalesPrice,TotalSalesQuantity,TotalSalesDollars,TotalExciseTax
0,8004,5287,0.98,2.0,9.800000e-01,0.10
1,9206,2773,0.99,1.0,9.900000e-01,0.05
2,3924,9123,0.99,2.0,1.980000e+00,0.10
3,3252,3933,0.99,2.0,1.980000e+00,0.10
4,10050,3623,1.98,2.0,1.980000e+00,0.10
...,...,...,...,...,...,...
11267,3960,3545,545778.28,135838.0,4.223108e+06,249587.83
11268,3960,4261,420050.01,200412.0,4.475973e+06,368242.80
11269,17035,8068,461140.15,187140.0,4.538121e+06,343854.07
11270,4425,3405,561512.37,160247.0,4.819073e+06,294438.66
11271,1128,1233,672819.31,142049.0,5.101920e+06,260999.20

In [139]:
vendors_sales_summary = pd.read_sql("""
WITH FreightSummary AS (
    SELECT 
        VendorNumber,
        SUM(Freight) AS FreightCost
    FROM vendor_invoice
    GROUP BY VendorNumber
),

PurchaseSummary AS (
    SELECT 
        p.VendorNumber,
        p.VendorName,
        p.Brand,
        p.Description,
        p.PurchasePrice,
        pp.Volume,
        pp.Price AS ActualPrice,
        SUM(p.Quantity) AS totalQuantity,
        SUM(p.Dollars) AS totalPPrice
    FROM purchases p
    JOIN purchase_prices pp
        ON p.Brand = pp.Brand
    WHERE p.PurchasePrice > 0
    GROUP BY 
        p.VendorNumber,
        p.VendorName,
        p.Brand,
        p.Description,
        p.PurchasePrice,
        pp.Volume,
        pp.Price
),

SalesSummary AS (
    SELECT 
        VendorNo,
        Brand,
        SUM(SalesPrice) AS TotalSalesPrice,
        SUM(SalesQuantity) AS TotalSalesQuantity,
        SUM(SalesDollars) AS TotalSalesDollars,
        SUM(ExciseTax) AS TotalExciseTax
    FROM sales
    GROUP BY VendorNo, Brand
)

SELECT 
    ps.VendorNumber,
    ps.VendorName,
    ps.Brand,
    ps.PurchasePrice,
    ps.Volume,
    ss.TotalSalesPrice,
    ss.TotalSalesQuantity,
    ss.TotalSalesDollars,
    ss.TotalExciseTax,
    ps.totalQuantity,
    ps.totalPPrice,
    fs.FreightCost,
    ps.ActualPrice,
    ps.Description
FROM PurchaseSummary ps
LEFT JOIN SalesSummary ss
    ON ps.VendorNumber = ss.VendorNo
    AND ps.Brand = ss.Brand
LEFT JOIN FreightSummary fs
    ON ps.VendorNumber = fs.VendorNumber
ORDER BY ss.TotalSalesDollars DESC
""", engine)

In [150]:
vendors_sales_summary.dtypes

VendorNumber            int64
VendorName             object
Brand                   int64
PurchasePrice         float64
Volume                float64
TotalSalesPrice       float64
TotalSalesQuantity    float64
TotalSalesDollars     float64
TotalExciseTax        float64
totalQuantity         float64
totalPPrice           float64
FreightCost           float64
ActualPrice           float64
Description            object
dtype: object

In [143]:
vendors_sales_summary.isnull().sum()

VendorNumber            0
VendorName              0
Brand                   0
PurchasePrice           0
Volume                  0
TotalSalesPrice       178
TotalSalesQuantity    178
TotalSalesDollars     178
TotalExciseTax        178
totalQuantity           0
totalPPrice             0
FreightCost             0
ActualPrice             0
Description             0
dtype: int64

In [145]:
vendors_sales_summary['Volume']=vendors_sales_summary['Volume'].astype('float64')

In [146]:
vendors_sales_summary.fillna(0,inplace=True)

In [147]:
vendors_sales_summary['VendorName']=vendors_sales_summary['VendorName'].str.strip()

In [155]:
vendors_sales_summary['GrossProfit']=vendors_sales_summary['TotalSalesDollars']-vendors_sales_summary['totalPPrice']

In [152]:
vendors_sales_summary

,VendorNumber,VendorName,Brand,PurchasePrice,Volume,TotalSalesPrice,TotalSalesQuantity,TotalSalesDollars,TotalExciseTax,totalQuantity,totalPPrice,FreightCost,ActualPrice,Description,GrossProfit
0,1128,BROWN-FORMAN CORP,1233,26.27,1750.0,672819.31,142049.0,5.101920e+06,260999.20,145080.0,3811251.60,68601.68,36.99,Jack Daniels No 7 Black,1290667.91
1,4425,MARTIGNETTI COMPANIES,3405,23.19,1750.0,561512.37,160247.0,4.819073e+06,294438.66,164038.0,3804041.22,144929.24,28.99,Tito's Handmade Vodka,1015032.27
2,17035,PERNOD RICARD USA,8068,18.24,1750.0,461140.15,187140.0,4.538121e+06,343854.07,187407.0,3418303.68,123780.22,24.99,Absolut 80 Proof,1119816.92
3,3960,DIAGEO NORTH AMERICA INC,4261,16.17,1750.0,420050.01,200412.0,4.475973e+06,368242.80,201682.0,3261197.94,257032.07,22.99,Capt Morgan Spiced Rum,1214774.94
4,3960,DIAGEO NORTH AMERICA INC,3545,21.89,1750.0,545778.28,135838.0,4.223108e+06,249587.83,138109.0,3023206.01,257032.07,29.99,Ketel One Vodka,1199901.61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,653,STATE WINE & SPIRITS,21394,24.01,500.0,0.00,0.0,0.000000e+00,0.00,12.0,288.12,8014.98,36.49,Stolpman Vyds L'Avion White,-288.12
10688,90047,CRUSH WINES,22737,5.84,750.0,0.00,0.0,0.000000e+00,0.00,24.0,140.16,1457.73,8.99,Rotation Chard,-140.16
10689,2242,DELICATO VINEYARDS INC,44339,8.90,750.0,0.00,0.0,0.000000e+00,0.00,12.0,106.80,7982.65,12.99,Irony Merlot Napa,-106.80
10690,1590,DIAGEO CHATEAU ESTATE WINES,13188,8.38,750.0,0.00,0.0,0.000000e+00,0.00,12.0,100.56,7259.75,12.99,Jade Mountain Merlot,-100.56
10691,3960,DIAGEO NORTH AMERICA INC,4397,9.44,750.0,0.00,0.0,0.000000e+00,0.00,1.0,9.44,257032.07,11.99,Capt Morgan Parrot Bay Mango,-9.44

In [156]:
vendors_sales_summary['ProfitMargin']=(vendors_sales_summary['GrossProfit']/vendors_sales_summary['TotalSalesDollars'])*100

In [161]:
vendors_sales_summary

,VendorNumber,VendorName,Brand,PurchasePrice,Volume,TotalSalesPrice,TotalSalesQuantity,TotalSalesDollars,TotalExciseTax,totalQuantity,totalPPrice,FreightCost,ActualPrice,Description,GrossProfit,ProfitMargin,StockTurnover,SalesTOPurchaseRatio
0,1128,BROWN-FORMAN CORP,1233,26.27,1750.0,672819.31,142049.0,5.101920e+06,260999.20,145080.0,3811251.60,68601.68,36.99,Jack Daniels No 7 Black,1290667.91,25.297693,0.979108,1.338647
1,4425,MARTIGNETTI COMPANIES,3405,23.19,1750.0,561512.37,160247.0,4.819073e+06,294438.66,164038.0,3804041.22,144929.24,28.99,Tito's Handmade Vodka,1015032.27,21.062810,0.976890,1.266830
2,17035,PERNOD RICARD USA,8068,18.24,1750.0,461140.15,187140.0,4.538121e+06,343854.07,187407.0,3418303.68,123780.22,24.99,Absolut 80 Proof,1119816.92,24.675786,0.998575,1.327594
3,3960,DIAGEO NORTH AMERICA INC,4261,16.17,1750.0,420050.01,200412.0,4.475973e+06,368242.80,201682.0,3261197.94,257032.07,22.99,Capt Morgan Spiced Rum,1214774.94,27.139908,0.993703,1.372493
4,3960,DIAGEO NORTH AMERICA INC,3545,21.89,1750.0,545778.28,135838.0,4.223108e+06,249587.83,138109.0,3023206.01,257032.07,29.99,Ketel One Vodka,1199901.61,28.412764,0.983556,1.396897
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,653,STATE WINE & SPIRITS,21394,24.01,500.0,0.00,0.0,0.000000e+00,0.00,12.0,288.12,8014.98,36.49,Stolpman Vyds L'Avion White,-288.12,-inf,0.000000,0.000000
10688,90047,CRUSH WINES,22737,5.84,750.0,0.00,0.0,0.000000e+00,0.00,24.0,140.16,1457.73,8.99,Rotation Chard,-140.16,-inf,0.000000,0.000000
10689,2242,DELICATO VINEYARDS INC,44339,8.90,750.0,0.00,0.0,0.000000e+00,0.00,12.0,106.80,7982.65,12.99,Irony Merlot Napa,-106.80,-inf,0.000000,0.000000
10690,1590,DIAGEO CHATEAU ESTATE WINES,13188,8.38,750.0,0.00,0.0,0.000000e+00,0.00,12.0,100.56,7259.75,12.99,Jade Mountain Merlot,-100.56,-inf,0.000000,0.000000
10691,3960,DIAGEO NORTH AMERICA INC,4397,9.44,750.0,0.00,0.0,0.000000e+00,0.00,1.0,9.44,257032.07,11.99,Capt Morgan Parrot Bay Mango,-9.44,-inf,0.000000,0.000000

In [158]:
vendors_sales_summary['StockTurnover']=vendors_sales_summary['TotalSalesQuantity']/vendors_sales_summary['totalQuantity']

In [160]:
vendors_sales_summary['SalesTOPurchaseRatio']=vendors_sales_summary['TotalSalesDollars']/vendors_sales_summary['totalPPrice']

In [1]:
print(1)

1